### ISSUE TITLE
Is there any support for multiple off chart plots, and if not can you add it.

### ISSUE THREAD

**Issue by AlexanderPeters** [C451/trading-vue-js#11]
If it's possible that would be amazing. I'd love to be able to have 10+ off-chart plots, this is an odd ask I know. The best way to implement this would probably be to implement a scrollbar along the side so that way you can move through the off-chart plots via scrolling while leaving the main chart in the same location. This would also require an option to move the bottom "time/vertical crosshair line label) to directly under the main chart instead of underneath the last off-chart plot, that way you would be able to scroll through the off chart plots while still being able to see the vertical crosshair label at the bottom of the main plot.

**Comment by C451** [comment]
I agree that would be amazing, but I think it's out of scope for now. May be in the future. Anyway I'll add it to the list.  

As a side note, I think this will make the layout even more complex. Another way to solve this is to introduce a headless mode with time-linking, so users can do whatever they want. 

Btw, thanks for creating a bunch of good issues!

**Comment by AlexanderPeters** [comment]
No problem, I'm just trying to figure out if this might finally be the project that's the goose capable of laying the golden egg that I need because one things for certain. I don't have a damn clue about how to code up any of this myself. You can give me a strongly typed programming language like Java and I'll give you the world, but anything remotely birthed out of the web just makes my head spin (html, css, javascript, xml, etc.).

**Comment by AlexanderPeters** [comment]
On second thought, might it be possible to implement this through a custom overlay like RSI. I might have to explore that. i.e I build an overlay that can accept a JSON file or parameters or whatever of either other overlays or javascript elements and builds them into a single element. Hmmm

**Comment by AlexanderPeters** [comment]
Better yet, how hard would it be for you to create an empty overlay of a user definable size. If the vertical size is larger than the default then implement a scroll bar on the size. Just a blank graphics canvas that can scroll. Then the user can define whatever functionality they want inside of that???

**Comment by C451** [comment]
it's just a small lib, but probably the most 'hackable' out there. 

>Better yet, how hard would it be for you to create an empty overlay of a user definable size.

I need to clarify: overlays live inside grids and currently there is no way to change grid size (it calculates automatically). This feature is definitely on the horizon.     

As a temp solution you can make a very tall chart (by setting a height bigger that the screen).

**Comment by C451** [comment]
Not on the map right now, closing.
