### ISSUE TITLE
Are overlays completely static objects.

### ISSUE THREAD

**Issue by AlexanderPeters** [C451/trading-vue-js#13]
Is there any way to add a method into an overlay which is periodically checked. For instance, I had the idea to hack together an overlay to solve my indicator switching issue. The intended behavior would go something like this, I'd make an overlay called indicator_switcher, which would place a small grey rectangle in the upper right corner of the graph and when clicked would execute some basic javascript code to swap the "offchart" section of the data.json file with the data needed for a different indicator (pulled from a separate JSON file) and save the data file. The app would then, of course, reload the chart with the new indicator; hacky but functional. -Eventually, multiple indicators could be stored in the other data file and it would just iterate through each one as you clicked the grey box again. I'm running into a few problems though. Most prominently I need to be able to have a method somewhere which is periodically checked. This would allow me to have some the code inside of it which changes the file run any time a conditional is met, most likely some form of is the cursor inside of the box + other parameters.

-So I ask is there any way to make part of an overlay's code dynamic, i.e. checked periodically, or are they simple an object definition which gets called once and nothing more.

**Comment by AlexanderPeters** [comment]
No, no they are not. I fooled myself into thinking the code was not executing, by not understanding where console.log() printouts in Node.js go to. Sorry for my ignorance, I'm a Java and Labview programmer who just learns other stuff by hacking other peoples code together; albeit learning slowly.

**Comment by laur89** [comment]
@AlexanderPeters care to share your indicator switching logic?
