### ISSUE TITLE
Anyway to get the state of the mouse other than position, i.e. clicked/clicking.

### ISSUE THREAD

**Issue by AlexanderPeters** [C451/trading-vue-js#14]
-I can get the cursor position data and if it is currently scrolling, but can I get any other data?
-Self-explanatory, would like to add a listener of some kind if at all possible.

**Comment by AlexanderPeters** [comment]
Edit: found out that the locked value at least on my mouse is a boolean if the middle mouse button is clicked. Supper useful would still be nice to have access to the info on the left and right mouse buttons, as well as maybe some other info on the scroll wheel like which direction is it scrolling.

**Comment by AlexanderPeters** [comment]
Ah ok, the locked value applies to all three buttons. My bad. Having scroll data would be useful though.

**Comment by C451** [comment]
Yes, it's on the list (all mouse events will be available)
