### ISSUE TITLE
Is there anyway to check keyboard states, i.e. up arrow is currently pressed.

### ISSUE THREAD

**Issue by AlexanderPeters** [C451/trading-vue-js#15]
-Self-explanatory, would like to add a listener of some kind if possible.

**Comment by C451** [comment]
For now you can listen to the keyboard from your App.vue and use Vue events to pass info to your overlays. I'll think about adding it as an API.

**Comment by DorothyRMartin** [comment]
I think pushing the 'right arrow' for moving the canvas 1 candle to the right is good.
Maybe shift+right arrow should move it 10 candles to the right

**Comment by C451** [comment]
> I think pushing the 'right arrow' for moving the canvas 1 candle to the right is good.
> Maybe shift+right arrow should move it 10 candles to the right

I assume that this particular behavior should be implemented on the application side (imagine that someone is already using arrows, and this will come as a surprise). However, It will be useful to be able to access keyboard events through the overlay API.  

I'm still thinking how to implement this in the possible best way.

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/commit/ead0e8ab4a7775ba8d50e95ed41586145a3a676d
