### ISSUE TITLE
Remove/increase cap on max zoom (show more candles in view)?

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#20]
I noticed this happens in the demo too:
https://c451.github.io/trading-vue-demo/

Is there a way to remove the cap on how far I can zoom out? Scrolling sideways is hard and doesn't work with a normal mouse scroll (two fingers sideways on macbooks), has to happen by dragging.

In some cases, such as 3 minute candles, it's really hard to find events that may have happened several days in the past. Would love to be able to zoom further out, beyond the current limit. Is it hardcoded somewhere?

**Comment by tiagosiebler** [comment]
Interestnig, if I zoom out slowly, I hit the limit and can't go further. If I zoom as quick as I can, it lets me snap past the limit. I guess it's a soft limit somewhere? :)

**Comment by C451** [comment]
Yep, it's hardcoded to be 1000 candles max (tradingview.com also has a similar limit)  
Do you want to see a slide show? Then you can try to change it in Constants https://github.com/C451/trading-vue-js/blob/master/src/stuff/constants.js

Update to 0.2.7, then:
```
import { Constants } from 'trading-vue-js'
Constants.ChartConfig.MAX_ZOOM = Infinity
```
:)

**Comment by tiagosiebler** [comment]
I've increased this to a new limit, though there still seems to be a hard limit somewhere. Does this ring a bell?

This is the maximum zoom I can manage, even then it's not consistent (sometimes I get this far, sometimes the unit at the bottom is 3-4 hours per tick):
<img width="1417" alt="Screenshot 2019-04-26 at 16 05 06" src="https://user-images.githubusercontent.com/14090872/56817266-2dab3700-683d-11e9-814b-7ac7104d4d4b.png">

The increase I did was pretty extreme, just to see where the limit might be:
<img width="733" alt="Screenshot 2019-04-26 at 16 05 23" src="https://user-images.githubusercontent.com/14090872/56817308-40257080-683d-11e9-9eef-e36c57487e65.png">

Where is MAX_ZOOM being read from? I can't seem to find it. Thanks!

**Comment by C451** [comment]
I forgot: update the repo (it was actually hardcore, but supposed to be from conf)

**Comment by C451** [comment]
> Scrolling sideways is hard and doesn't work with a normal mouse scroll 
Can you elaborate?
Does the mouse wheel work? (I assume you are using an apple mouse)

**Comment by tiagosiebler** [comment]
> > Scrolling sideways is hard and doesn't work with a normal mouse scroll
> 
> Can you elaborate?
> Does the mouse "wheel" work? (I assume you are using an apple mouse)

Certainly. I'm using an apple laptop, where I can scroll using two fingers. If I scroll vertically, it zooms the candle range (in & out), locked to the right-most candle.

Trying to scroll left<->right seems to confuse it, doing something similar to the vertical scroll, but in a very messy way.

Trying to pinch-zoom isn't smooth either, instead it triggers a sudden min-max transition. Hope the description makes sense :)

**Comment by C451** [comment]
Thanks, I need to test it. I prefer mouse for trading (love precision)

**Comment by tiagosiebler** [comment]
Fair enough, I'm on the side of automating as much as possible, so often the laptop's most convenient (and the scrolling on macbook mousepads is superb) 👍

**Comment by tiagosiebler** [comment]
The zoom seems to be working much better, thank you! Also hooked up some of the indicators, I love that everything's automatic. 

One very very **very minor** observation is the zoom seems slightly inconsistent. You can see here, the indicator seems shifted-slightly to the right of the last candle:
<img width="1419" alt="Screenshot 2019-04-26 at 17 06 58" src="https://user-images.githubusercontent.com/14090872/56821312-d362a400-6845-11e9-848a-2032fa82ad8f.png">

If I zoom in and move it to the left, it fits correctly:
<img width="1430" alt="Screenshot 2019-04-26 at 17 08 30" src="https://user-images.githubusercontent.com/14090872/56821351-f2613600-6845-11e9-8e3b-d3ad88d8f4a3.png">

If I move the same view to the right, you see the offset again:
<img width="1441" alt="Screenshot 2019-04-26 at 17 09 06" src="https://user-images.githubusercontent.com/14090872/56821375-0442d900-6846-11e9-8823-b4aeea1e8615.png">

But this is very very minor, something about how the zooming works. Other than that, this is beautiful, thank you for building this! I can dynamically hook up any signals or indicators generated by my engine, and it just looks great! All I have to do is transform my data, the rest is magic 🥇

**Comment by C451** [comment]
> I can dynamically hook up any signals or indicators generated by my engine, and it just looks great!
I'm really glad that my lib is useful! 

Year it's known _issue_. This is caused by the calculation method of ** y-range **: I calc it according to the candlestick data, and TradingView does it based on all indicators. Interestingly, in some cases my method shows a clearer picture (e.g. huge drop + slow ema).

 May be it's a good idea to allow users to choose.

**Comment by tiagosiebler** [comment]
Want me to close this issue and spawn specific issues for what came out of this, or happy to use this post as reference? I think this is a summary of what we discussed:
- [ ] Docs specifying max zoom range (and that Infinity works, very well!!)
- [ ] Sideways scrolling should do the same as mouse-drag left<->right, instead it triggers sporadic zooming.
- [ ] Indicator lines don't seem to consistently zoom with candles (post above this one).

**Comment by C451** [comment]
Let's keep the first two be here, and the last in a new issue.

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/commit/923a7374d451475cbf44b9817be2a40b461e0ae5

closes mac trackpad. Check this out, should work smooth af.

**Comment by tiagosiebler** [comment]
Sweet, nicely done. Can confirm, smooth AF. Thanks!!
