### ISSUE TITLE
onClick & onHover for overlays/signals?

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#21]
I'm rendering trades/signals on the chart, is it possible to react to onClick or onHover events?

Looking to display tooltips and other useful menus. Thanks!

**Comment by C451** [comment]
It will be possible soon, already in the issues ;)

**Comment by tiagosiebler** [comment]
Awesome! Do you have an issues list, or is it on your machine? :)

**Comment by C451** [comment]
There are so many, so I keep them in three places: TODOs, git issues & my head :)

**Comment by tiagosiebler** [comment]
That's fair, I thoroughly recommend the "Projects" feature, if the list is changing rapidly :)
https://github.com/C451/trading-vue-js/projects

**Comment by C451** [comment]
Thanks, I will look into it. Mastering Github :)
