### ISSUE TITLE
 Indicator lines don't seem to consistently zoom with candles

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#22]
Spawned from #20. One very very **very minor** observation is the zoom seems slightly inconsistent. You can see here, the indicator seems shifted-slightly to the right of the last candle:
<img width="1419" alt="Screenshot 2019-04-26 at 17 06 58" src="https://user-images.githubusercontent.com/14090872/56821312-d362a400-6845-11e9-848a-2032fa82ad8f.png">

If I zoom in and move it to the left, it fits correctly:
<img width="1430" alt="Screenshot 2019-04-26 at 17 08 30" src="https://user-images.githubusercontent.com/14090872/56821351-f2613600-6845-11e9-8e3b-d3ad88d8f4a3.png">

If I move the same view to the right, you see the offset again:
<img width="1441" alt="Screenshot 2019-04-26 at 17 09 06" src="https://user-images.githubusercontent.com/14090872/56821375-0442d900-6846-11e9-8823-b4aeea1e8615.png">

But this is very very minor, something about how the zooming works.

**Comment by C451** [comment]
I don't think it's very minor though. Could you post your data-set (without trades) to reproduce the problem? Github gist will be perfect.

**Comment by tiagosiebler** [comment]
Absolutely, trades are lazily included if that's okay:
https://gist.github.com/tiagosiebler/2356a4f4f291f45a2fb5d1b6f8e3c5d3

**Comment by C451** [comment]
It turned out that  it's a duplicate of #17 
Do you have missing candles? That's an exact issue I'm working on today.

**Comment by tiagosiebler** [comment]
Missing candles are possible, as my dataset is limited to what the exchange has available, and the exchange may have time gaps (e.g downtime). In this example, data's based on candles from the crypto exchange, binance.

**Comment by tiagosiebler** [comment]
The candle count and indicator value count should be a match though, should be an equal number of rows.

**Comment by C451** [comment]
Yeah, it's all about my candle-rendering method.

**Comment by C451** [comment]
You can update the repo and check - it should be ok now.

**Comment by tiagosiebler** [comment]
Looks great! Thank you, nice work!
