### ISSUE TITLE
2h candles aren't showing?

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#23]
I have 2h candles, for some reason they're not rendering. Can you try?

30m candles in the same flow are fine. 

2h Data object:
https://gist.github.com/tiagosiebler/6c1fe7cb89997834f44bb508131074c3

**Comment by C451** [comment]
Yes, something is wrong. Candles are thin and zooming doesn't work. Coding is fun!

**Comment by C451** [comment]
It's caused by the same last to candles. My algo calculates the interval between two first and two last candles and takes the minimum. I thought it will be robust :))

**Comment by tiagosiebler** [comment]
Ah interesting, duplicate data from my engine! Curious what caused this :)

**Comment by C451** [comment]
Dark secrets are hidden in the code. Imagine how many of them are in the world's code base :)

**Comment by C451** [comment]
Btw algos without a clear stops are really dangerous. I was running a similar algo a year ago, didn't like the drawdowns. (Hope yours has some kind of emergency stop)

**Comment by tiagosiebler** [comment]
Oh yes ignore the data here, it's just one of the more "raw" results from a generation system - appreciate the comment though :)

**Comment by C451** [comment]
Made the algo better.
