### ISSUE TITLE
0:100 binary indicators not showing

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#24]
Is it possible to show indicators that flip between 0 and 100 (and nothing in between)? 

Example indicator dataset with candles:
https://gist.github.com/tiagosiebler/5695f318d1ffde90c151a0472fc36b04

I'm seeing a white view instead (last section):
<img width="1634" alt="Screenshot 2019-04-26 at 23 46 38" src="https://user-images.githubusercontent.com/14090872/56840146-d8434a00-687d-11e9-882e-f7d7c04eb03f.png">

If the "Spline" type doesn't suffice for that, is there another that would better fit this kind of indicator?

**Comment by C451** [comment]
Use RSI for now. And the lib doesn't understand your timestamps (1548543599999) because they must be in UTC and rounded.

**Comment by C451** [comment]
Your screenshots seem to be blurry. How does this look on your screen? I suppose you have a retina + an external monitor. Could you also check on the macbook's screen if so?

**Comment by tiagosiebler** [comment]
I'll adjust the timestamps and try the rsi type tomorrow. I think the blur might be the uploaded picture quality trimmed by github.

**Comment by tiagosiebler** [comment]
Have you thought about trying to detect data type automatically, for indicators? A min max might suffice to determine a default, if type isn't provided.

**Comment by C451** [comment]
Haven't thought about it. It seems like a good old dilemma "strong types vs dynamic types". I don't want to make users too lazy. :) 

Spline should work here, though, need to check it.

**Comment by tiagosiebler** [comment]
I always weigh between is it lazy, or does it reduce/avoid repeated code? Choice is yours of course, and thanks for the commit!
