### ISSUE TITLE
Button(s) to move/merge indicators up/down into/above/below views

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#25]
Mini enhancement request, if you find the time - similar to tradingview, even if temporary until the page is reloaded.

**Comment by C451** [comment]
I decided to limit the lib functionality by a simple rule: **it should not modify the data, only display**.

Thus, this should be implemented in your application. But I think it would be fair to add buttons with event callbacks.

**Comment by tiagosiebler** [comment]
I like the idea of helpers and callbacks. That makes manipulation opt in, while you provide the tools and hooks to make building something easier.

**Comment by C451** [comment]
Exactly.
