### ISSUE TITLE
Changing constants in the minimal example?

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#26]
Is it possible to change some of the constants, like the ChartConfig.MAX_ZOOM, without having to rebuild the trading-vue library, e.g within the scope of this minimal sample?
https://github.com/C451/trading-vue-js#how-to-use

**Comment by C451** [comment]
That's what I'm thinking about, how to add this without rewriting too much code.

**Comment by tiagosiebler** [comment]
My first thought was similar to the data() fn responsible for fetching data, there could be a config fn that returns the defaults....by default, and exposes a way to mod them on the fly?

```
config() {
  var defaultConfig = TradingVue.ConfigDefaults;
  defaultConfig.constants.MAX_ZOOM = Infinity;
  return defaultConfig;
}
```

**Comment by C451** [comment]
Yeah, thanks for the suggestion. Something similar to this, but I'd prefer to make a custom config for each TradingVue instance (in case someone wants to have multiple charts with different settings).

**Comment by tiagosiebler** [comment]
That would be ideal!

**Comment by tiagosiebler** [comment]
Thanks @C451!

**Comment by C451** [comment]
More updates are coming ;) Was busy buying the dips
