### ISSUE TITLE
Change the color of specific candles

### ISSUE THREAD

**Issue by DorothyRMartin** [C451/trading-vue-js#28]
How do make certain candles specific colors ? 
Obviously color coding candles that denote strength and weakness is a pretty important and useful feature, I cannot see how to do this without redrawing another fake candle ontop of the existing one, it feels like there should be an optional 'color' parameter at the end of each data entry set 

What do you think as preferred solution to this ?

**Comment by C451** [comment]
Yes, I see the need for this. I plan to make a customisable **Candlestick** overlay, where you can add  additional parameters. But I'll keep the basic interface simple.

**Comment by C451** [comment]
Now you can!

Update to 0.3.3 and see https://github.com/C451/trading-vue-js/tree/master/docs/overlays#candles
