### ISSUE TITLE
Provide way to switch between different candle sizes and types, if available

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#30]
If I provided ohlcv arrays for 15m and 30m candles, I'd love for a way to switch between them. This effectively allows a way to navigate trades that happened over bigger timeframes, from different levels of detail.

Combined with the data getters (when reaching a scroll limit of available data), this could be a pretty nifty feature.

**Comment by C451** [comment]
Have you seen https://github.com/C451/trading-vue-js/blob/master/test/tests/Timeframes.vue? :)

**Comment by C451** [comment]
Btw, if you have some free time and the a desire to push the development, you could help with data helpers (basically it's a separate class dealing with the data).

Also, appreciate your feedback, helps to understand the direction better.

**Comment by tiagosiebler** [comment]
Wow that is very cool, did not see that before. Thanks! About contributing, would love to but time's already a limitation with so many things to play with :-( if you open a github issue with the "help wanted" label, summarising the needs, perhaps one of the growing number of fans can help out too?

**Comment by C451** [comment]
> bout contributing, would love to but time's already a limitation with so many things to play with

"Time is the only luxury" (c) Kanye :)
