### ISSUE TITLE
Replace 'trade markers' with a more generic markers

### ISSUE THREAD

**Issue by DorothyRMartin** [C451/trading-vue-js#31]
I like the trade markers. They're great.   But often, you just want to also put markers at other random points, on the chart to highlight things for whatever reason.

This is why I think the 'trade marker' should just be abstracted into a more generic 'marker' on-chart display and you just set the marker you want to use.

Maybe something like.. . 
  
```
onchart { 
	'drawings': [
		{
			'name': 'my first set of markers'
			'type': 'marker'
			'data': [ 
				[x,y],
			]
			'settings': {
				'marker': '↑'
				'color': '#A2FF00'
				...etc 
			}

		}
	]
}
```

**Comment by C451** [comment]
Thanks for the suggestion, of course, I thought about this, but I'm kinda short on time now. The main priority is to make an extended data structure to provide greater freedom for users (e.g. see your previous issue about custom candles).

Meanwhile you can easily implement your own marker class! And it's really easy if you know the canvas API. This library called **hackable** for a reason.

**Comment by DorothyRMartin** [comment]
I'm new to npm/vue. 
I did manage to get this running, however the grin example didn't work for me.
I will have a play, I would love to contribute more in terms of overlays etc

**Comment by C451** [comment]
Have you tried trading-vue-101 ? 

Yeah, if you create an advanced marker overlay (or something else) I'd love to add it in the collection.

**Comment by DorothyRMartin** [comment]
Yes I did get the grin running on the 101, will keep trying and playing with it see if I can ultimately add some value to this project. Which I would like to do because this is imo the best plotting library there is right now. 

Few other things of importance of course, multiple y axis on each chart 'pane', feeding in real time data, good for live or 'playback' etc etc. .  but yeah this project is ace. I tell everyone about it .

**Comment by C451** [comment]
Great! 

The project was designed specifically to be easy-expandable. And even at this stage almost every possible indicator could be implemented. However, I'd like to focus more on the implementation of the building blocks, because the main goal of the project is to be expressive. Custom y-axis is on the map for sure. 

I hope to push some updates next week.  

Thanks for promoting the stuff!

**Comment by C451** [comment]
A custom overlay is needed.
