### ISSUE TITLE
Running on remote server

### ISSUE THREAD

**Issue by DorothyRMartin** [C451/trading-vue-js#33]
I know this is going to sound weird, but how the fuck can I run this on my remote machine.
localhost just isn't my development server. . 
How can I add my local host to this to get it to allow access from my other machine ?

**Comment by C451** [comment]
It's totally possible but you need to write a custom app. Install the library with **npm** or even with a script tag: https://github.com/C451/trading-vue-js/blob/master/dist/trading-vue.min.js

Alternatively, you can share this development version by configuring the WebPack port  https://webpack.js.org/configuration/dev-server/ and opening it in firewall, but this is probably a **bad** idea coz you sacrifice your security.
