### ISSUE TITLE
Multiple colours in one series

### ISSUE THREAD

**Issue by tiagosiebler** [C451/trading-vue-js#34]
Hello again!

I saw you can set a colour for a whole series:
```
{
    "name": "EMA, 25",
    "type": "EMA",
    "data": [
        [ 1551128400000, 3091 ],
        [ 1551132000000, 3112 ],
        [ 1551135600000, 3105 ]
    ],
    "settings": {
        "color": "#42b28a"
    }
},
```

Would it be possible to optionally run different colours through different parts of a series?

One way I imagine this:
```
{
    "name": "EMA, 25",
    "type": "EMA",
    "data": [
        [ 1551128400000, 3091, '#50b242' ],
        [ 1551132000000, 3112, ' #50b242' ],
        [ 1551135600000, 3105, '#b24242' ]
    ]
},
```

**Comment by C451** [comment]
Hi,

I really think you should give a try to the custom overlay system. It requires 15 min to create an a new overlay :)

https://github.com/C451/trading-vue-js/blob/master/src/components/overlays/Spline.vue

1. Extend Spline class, called it **AugSpline** or smth 

2. Read the color as **p[2]**  and apply ```ctx.strokeStyle = p[2]```

3. Add **AugSpline** to **overlays** prop as class

Boom!

**Comment by tiagosiebler** [comment]
Thanks for the pointer! Will play with it
