### ISSUE TITLE
event catched multi times

### ISSUE THREAD

**Issue by khyoz** [C451/trading-vue-js#37]
Hi,
I have changed the Grin example (now I understand how overlays useful are ;o) and I have added a small line to get the screen position..
` 
draw(ctx) {

            const l = this.$props.layout

            console.log(this.$props.cursor.y$); // added
`
But I can see in debug that this is displayed several times on 1 click...
Is that normal ?
![bug-tradingvue-multievents-2019-07-18_070615](https://user-images.githubusercontent.com/26684951/61430756-4a7e7480-a92b-11e9-85ec-3b97936c550a.png)

**Comment by C451** [comment]
> now I understand how overlays useful are

Oh yes, I personally think that this is a very underrated feature. :D 

Thank you for the discovery, there are two wasted draw calls (I guess one of them appeared after the transition to Data Structure v1.1). 

However you shouldn't rely on the order or frequency of draw() calls, you can think of this function in more declarative way.

**Comment by C451** [comment]
Fixed https://github.com/C451/trading-vue-js/commit/b4542713684aa487268778ee411d7c83adc89192
