### ISSUE TITLE
Empty dates in the future ?

### ISSUE THREAD

**Issue by khyoz** [C451/trading-vue-js#38]
Hi, 
I'm thinking about implementing an Ichimoku indicator. I need to draw data in the future (like kumo SSA / SSB) and also prediction prices/dates. I don't ask you to do it, but I would like to know if there is a simple way to draw dates in the future, with empty values? At the moment the crosshair is locked after the last candle, and if I try to put empty ohlc values after a date in the data file, the screen is black and not rendered.
Is that something already in your task list or do you have some ideas in mind so I could try to do it myself ?
Also, if there was a simple toolbox example, that would help me a lot to create other stuff like :
drawing a line between 2 selected points or in the future
Thanks for your ideas, your project rocks ! really !

**Comment by C451** [comment]
> I'm thinking about implementing an Ichimoku indicator

Hi, this is a great idea! Yeah, I'll fix crosshair ASAP, empty candles sounds like a hack that is too dirty even for this lib.

A toolbox is on its way. And an extendable drawing-tool overlays. Now the list of priorities looks like this:

- Data Helpers
- Toolbox & drawing tools
- Performance

Thanks for spotting issues! There is always some tricky stuff in the code.

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/commit/6e1deeae47f1c20ed03f36f8943f56d6848c481c and https://github.com/C451/trading-vue-js/commit/f191995ae462c4165fb55f5b3562687b16aad4db

**Comment by C451** [comment]
Let me know if there are any glitches. Look fine to me.

If you decide to share your Ichimoku overlay, it will be great. Also, I got an idea that we can add indicator calculations as an extension of the data helper class so that people can pack everything they need into one slick class.

**Comment by khyoz** [comment]
yes sure, I can share the ichimoku overlay once I have it done, no problem ! But don't expect it in the next 24h, lol 
Your idea looks great as well ! Great feature and future for Trading-vue ! Maybe one day, you will open a discord or telegram session for people to discuss and share, but it's not urgent ! I just discovered your package... and just can imagine the potential !

**Comment by C451** [comment]
> But don't expect it in the next 24h, lol

Sure, this project is very chill!

**Comment by khyoz** [comment]
change is working ! Cool, Thanks
