### ISSUE TITLE
how to hide the Sidebar

### ISSUE THREAD

**Issue by yangqihua** [C451/trading-vue-js#46]
hello. can i hide the  Sidebar?

**Comment by C451** [comment]
Hi, only with `overflow: hidden` for now.

**Comment by yangqihua** [comment]
can you describe more detail ?

**Comment by yangqihua** [comment]
I want candle chart get 100% with of the screen without sidebar

**Comment by C451** [comment]
Something like this: 
```
<div style="width:100%; overflow:hidden">
   <trading-vue style="width:calc(100% + 60px)"></trading-vue>
</div>
```
Basically, you can do it with pure css. In the future I will add this feature.
