### ISSUE TITLE
Dealing with local time zone when formatting the date

### ISSUE THREAD

**Issue by char101** [C451/trading-vue-js#50]
Hi,

In `format_date`, when creating a new `Date` from epoch, the hour is shifted for as much as the timezone offset.

For example, in my timezone

```javascript
new Date(1562803200000)
// Date Thu Jul 11 2019 07:00:00 GMT+0700 (Western Indonesia Time)
```

I could offset the epoch to deal with the hour, but it will cause problem when dividing the epoch with time time step, because it might not be divisible.

An easy solution would be to just add `new Date().getTimezoneOffset()` to `t` before formatting the date. This will ensure proper date/hour and division of the time step.

```javascript
format_date(t) {
        t = t + (new Date().getTimezoneOffset() * 60000)
        let d = new Date(t)
```

**Comment by C451** [comment]
Yeah, the current timeline implantation is total mess. Tons of issues to be resolved. I'll look into your suggestion.

**Comment by C451** [comment]
Yeah, the current timeline implementation is in total mess. Tons of issues to be resolved. I'll look into your suggestion.

**Comment by C451** [comment]
Nice! Surprisingly, It works well with so little effort. Will add it as a fix for now. Thanks, @char101 !

**Comment by black-hawk85** [comment]
Hi,

why don't you use moment library for this?
You could solve this issue in one line and wouldn't have to bother about timezones.

```
format_date(t) {
  return moment.utc(t).format('HH:mm')
}
```

**Comment by C451** [comment]
> Hi,
> 
> why don't you use moment library for this?
> You could solve this issue in one line and wouldn't have to bother about timezones.
> 
> ```
> format_date(t) {
>   return moment.utc(t).format('HH:mm')
> }
> ```

Yeah, I'll give it a try sometimes. But usually I prefer to have less dependencies.

**Comment by black-hawk85** [comment]
Can understand that. But I saw in your package.json you already have moment as dependency

**Comment by OnlyC** [comment]
I use date-fns instead of moment.js because of the size.

**Comment by adsonvinicius** [comment]
@char101 do you tried on real-time updates? When I fetch data the chart is plotted fine, the botbar and x-axis shows the time on my current timezone (UTC-3) but when the chart updates (price/volume) a new candle is created but at that time using UTC+0 then it skips in a total mess. Do you have any idea where can I do?

**Comment by char101** [comment]
@adsonvinicius Sorry I am not currently using this library. Maybe @C451 can help.

**Comment by adsonvinicius** [comment]
@char101 he is developping this feature for 1.0.0 version. I asked you as workaround. But okay I will keep trying to figure out a way. Thanks!

**Comment by marcossapp** [comment]
@adsonvinicius, maybe @C451 can suggest where to change on chart update method to allow this timezone issue. I am using another library for real-time.

@char101 aren't you using this library it means you're using another one? If yes which one? I am looking for other libraries for a benchmark.

**Comment by char101** [comment]
I'm using techan-js. I'm not plotting real time data and performance is not an issue. Since D3 is DOM based, I can modify it freely with the D3 API. With canvas, the customization that can be done without modifying the library code is more limited.
