### ISSUE TITLE
When changing zoom factor, sometimes the weekend dates is displayed

### ISSUE THREAD

**Issue by char101** [C451/trading-vue-js#51]
Hi,

First, I changed the value of `GRIDX` to 20 because I want to show all the dates in a daily chart.

![A](https://user-images.githubusercontent.com/71255/64473679-e42c0a80-d193-11e9-9bab-dc7438beaf8e.png)

When changing the zoom factor via the mousewheel, sometimes the weekend dates is being displayed.

![C](https://user-images.githubusercontent.com/71255/64473709-3cfba300-d194-11e9-85aa-67ce4d47b546.png)

**Comment by C451** [comment]
I saw this too, the reason is the grid augmentation algo:  https://github.com/C451/trading-vue-js/blob/master/src/components/js/grid_maker.js#L193 

Need to improve this.

**Comment by char101** [comment]
Thanks for the pointer. From a bit of debugging I found that the weekend grid is shown if `extend_left` push a value to `xs`. If `extend_left` doesn't push any value the weekend days is not shown.

I personally prefer that date without value is hidden (just like the weekend days), so for my solution I'll simply comment the mentioned lines.

Also I rather like the weekend/holiday gap since from my observeration people seem to like to buy on monday and sell on friday (shorting is rare in my country). So although it is uncommon to show weekend gaps, for some people it could be a feature.

**Comment by C451** [comment]
Yes, this needs to be reviewed.
