### ISSUE TITLE
Second level for the x-axis

### ISSUE THREAD

**Issue by char101** [C451/trading-vue-js#52]
Hi,

Just a suggestion but I think it will be useful to make the x-axis into two part (two lines), the first part showing the points and the 2nd part showing a higher time step.

With daily chart, first line = days, second line = month
With hourly chart, first line = hour, second line = day
With minute chart, first line = minute, second line = hour

For example with daily chart:
```
25 26 27 28 29 30 1 2 3 4 5 <- 1st line
                 Aug        <- 2nd line
```

**Comment by C451** [comment]
Look, I follow tradingview.com for the most part (design, UX etc). Can we do better? Probably. But Is it worth it? 

The scale of this project is not that big. For comparison, the tradingview.com guys spent over two decades (as far as I know) polishing their charting platforms. I don't have the same resources/time for this project.  

So, unfortunately, this is beyond the scope.

**Comment by tiagosiebler** [comment]
This kind of feature would be useful, if you @char101 or anyone else watching is able to help, please do! @C451 doesnt need to build this wonderful project all alone :-)

**Comment by C451** [comment]
@tiagosiebler Haha, this is gold!

**Comment by char101** [comment]
I can probably implement it myself but since @C451 has stated that he is following tradingview's UX then it won't be merged into this project. Maybe I'll implement it in my local clone sometime. It is not really important feature though.

**Comment by C451** [comment]
@char101 A good idea. My biggest concern is the build size. I'd like to save some space for the  roadmap features (there is a lot to do). After v1 we could include some nice additional goodies. 

@tiagosiebler The biggest problem with the adoption is the size of the intersection between two groups: sophisticated traders and vue.js developers. As you can guess, it's very small.
