### ISSUE TITLE
Crosshair: use a transparent line instead of dashed line for the vertical part

### ISSUE THREAD

**Issue by char101** [C451/trading-vue-js#54]
Because using a dashed line obscure the wicks.

Example:
![2019-09-08 11_53_57-chart](https://user-images.githubusercontent.com/71255/64483608-89e08780-d22f-11e9-8580-af016fa1bd44.png)

By the way from the screenshot it seems that the box width for the volume is a bit larger than the candle.

My modification (hardcoded values):
```diff
diff --git a/src/components/js/crosshair.js b/src/components/js/crosshair.js
index 551535f..261300d 100644
--- a/src/components/js/crosshair.js
+++ b/src/components/js/crosshair.js
@@ -39,8 +39,14 @@ export default class Crosshair {
             ctx.moveTo(0, this.y)
             ctx.lineTo(this.layout.width - 0.5, this.y)
         }
+        ctx.stroke()
+        ctx.restore()

         // V
+        ctx.save()
+        ctx.beginPath()
+        ctx.strokeStyle = 'rgba(255, 255, 255, 0.1)'
+        ctx.lineWidth = 10
         ctx.moveTo(this.x, 0)
         ctx.lineTo(this.x, this.layout.height)
         ctx.stroke()
```

**Comment by char101** [comment]
I found that the misalignment between the candle and the volume bar is from the `0.5` in this line https://github.com/C451/trading-vue-js/blob/master/src/components/js/layout.js#L69

If the `0.5` is removed, the bars are aligned.

**Comment by C451** [comment]
I'm afraid this is not possible: the layouts for candles and volbars are different. The same thing with tv.com : 
![tv com](https://user-images.githubusercontent.com/48596328/64485947-7df4c580-d22f-11e9-843d-9d4fce2ae514.png)

**Comment by char101** [comment]
Yeah, I have tried several method with no luck. Also I will close this issue since it does not follow tradingview design.
