### ISSUE TITLE
how to remove the line vertical in grid?

### ISSUE THREAD

**Issue by learntolearn99** [C451/trading-vue-js#55]
How to remove these lines vertical?
![Screenshot_2019-09-08 C451 trading-vue-js(1)](https://user-images.githubusercontent.com/54758734/64486792-f8d3d580-d25b-11e9-81d7-d3fe5a03b8da.png)

**Comment by C451** [comment]
It can be removed only with the entire grid: set the grid color to `transparent`. https://github.com/C451/trading-vue-js/blob/master/src/TradingVue.vue#L55

**Comment by thenewspacesky1990** [comment]
Hi @C451 
I just want to remove the vertical line  and keep the horizontal line

**Comment by C451** [comment]
There no API for that for now, but I can suggest you a little hack: add 1ms to every timestamp in your dataset.

**Comment by learntolearn99** [comment]
Hi @learntolearn99 
Could you tell me more detail?
Thanks

**Comment by C451** [comment]
```
[1539016200001,0.49395,0.49497,0.49125,0.49319,2483674.4],[1539018000001,0.49319,0.49385,0.49177,0.4932,1802643],[1539019800001,0.49311,0.494,0.4925,0.49337,1591872],
...
```
Remember, this is a hack, not the proper solution.
