### ISSUE TITLE
Please make an example use socket to update chart realtime

### ISSUE THREAD

**Issue by learntolearn99** [C451/trading-vue-js#56]

**Comment by C451** [comment]
I'll update this https://github.com/C451/trading-vue-js/blob/master/test/tests/DataHelper.vue . First I need to implement several handful DataCube features.

**Comment by learntolearn99** [comment]
@C451 
Please update soon as possible. Thanks

**Comment by C451** [comment]
@learntolearn99 I believe in quality vs quantity. So no rush here.
