### ISSUE TITLE
Wow what a discovery. Charting God. Please never sell this.

### ISSUE THREAD

**Issue by stoxalpha** [C451/trading-vue-js#57]
Hey,
       Amazing library. However I am more of server side guys with basic js working knowledge. Could follow your guide to create my first chart, however need to use this one of template framework such as freemarker, etc with Spring Boot/Framework. Would help if this can be added to how this can be done easily.

**Comment by C451** [comment]
Hey, 

It's impossible to sell what's already free :D Thanks for the kind words, though!

I'm not familiar with Spring, but there are probably some adapters (like this one https://github.com/jonashackt/spring-boot-vuejs ? ) .

**Comment by stoxalpha** [comment]
Hey thanks for the quick reply. Once again awesome job and thanks. What i meant is could you share the most conciese html code that works as is on a http server. And i need to access data via  multiple different web services instead of a file. How do I do that?

**Comment by C451** [comment]
Yes, here is the simplest form of using TVjs : https://github.com/C451/trading-vue-demo

This is just a plain html with no pre-processing etc (although you need to include Vue.js and TVjs). You can share it with any http-server. Is this what you are looking for?

**Comment by stoxalpha** [comment]
oh nice! Also last question for now 😄 How do i use the json data from webservice instead from a file. Many kudos to uou

**Comment by C451** [comment]
It depends on your app architecture, but if you are going to display the chart on the same domain as you webservice, then you can you `fetch` or `axios` for pulling data. 

Btw, is there any specific reason why you decided to use this lib? It will much easier to use tradingview.com itself or their lightweight lib for displaying stock data: https://github.com/tradingview/lightweight-charts

This lib still has bad support for stock charts: https://github.com/C451/trading-vue-js/issues/36

**Comment by stoxalpha** [comment]
well i am developing an algo trading platform and see the real potential of what you have created. i see the power of it but i believe it  just needs more supporting docs for layman to js world.

**Comment by va-prans** [comment]
You should make an API service in spring that returns raw data in the vuejs data format.

**Comment by C451** [comment]
Classic: developing new features is always more exiting than documenting old ones. :)
