### ISSUE TITLE
When there is only one price in the OHLC, the candles are not shown

### ISSUE THREAD

**Issue by char101** [C451/trading-vue-js#58]
Hi,

All OHLC value in this stock is 50, so I expect a horizontal line somewhere in the middle, but what happens is that there is no candle (or line) at all. It seems the whole y-axis become the point for 50.

![AA](https://user-images.githubusercontent.com/71255/64692631-d17d4280-d4bf-11e9-8a5d-7f0e88f03083.png)

**Comment by C451** [comment]
Hi, share the dataset please.

**Comment by char101** [comment]
Hi,

Below is two example dataset. Both are similar with one difference, one has a single day where there is a high price which is different from the other price. Otherwise all the prices are 50. This are data from real stocks.

[stock.zip](https://github.com/C451/trading-vue-js/files/3603259/stock.zip)

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/commit/66ce2056b0d478413de64e5ee1c257be05c347d8 fixes it.
