### ISSUE TITLE
how to update data chart realtime with socket

### ISSUE THREAD

**Issue by zmohamed200133** [C451/trading-vue-js#60]

**Comment by C451** [comment]
Unstable: https://github.com/C451/trading-vue-js/blob/master/src/helpers/datacube.js#L129

**Comment by learntolearn99** [comment]
hi @C451 .
Could you make an example ?
Thanks

**Comment by C451** [comment]
@learntolearn99 Yeah, will make soon.

**Comment by BusinessDuck** [comment]
Any updates with it? Now its look unstable, why chart `layout` update move time axis on each added new candle, looks strange.

https://user-images.githubusercontent.com/10143411/176896012-13b0ca56-6fa1-49d6-89a8-bdafb7320e9f.mp4

**Comment by ismaelliang** [comment]
@BusinessDuck Hi, did u find a solution?
