### ISSUE TITLE
Questions by a beginner

### ISSUE THREAD

**Issue by Tiernan9** [C451/trading-vue-js#61]
Hi ! 

I've just looked at TV by testing it (the examples in the README and also in /test) and I have to say that it's a really great job with really interesting features one can add (compared to tradingview). I am new and trying to understand the structure, therefore I may have basic questions if you may.  Would you mind to correct me if I am wrong about this large view of it : 

Basically, one could add any data markets API (I don't know yet where to set it up. I was wondering about the structure of the csv or json files which may differ from different sources), TV will plot them and allow one to add indicators (calculated separately with the datacube : datacube would calculate them mostly with only the values displayed on screen to optimize calculation time) and also drawing tools (not yet implemented).  So for now on it would allow one to display prices and some drawings. 

Will it be possible 
- to place orders with it ?  
- to allow statistical analysis (which could be done using Python and then displayed with the help of TV) ? 
- (linked to the former point) to do algorithm trading ?  

To understand how it works, I've seen that the complex Ichimoku indicator has been implemented, I will try to reproduce it by myself, and then looked at ways to do/implement/link to statistical analysis (I guess that then algorithm trading will follow - I'm not saying that all of that will be easy, not at all).

Thanks in any case, I will spend time to look at it ! 

PS : in your simple example, I have tried to draw a line between the entry point and the exit ones, but results were only vertical or horizontal lines.

**Comment by C451** [comment]
Hi and welcome!

I'll try to cover all your questions:

- TV has its own data format https://github.com/C451/trading-vue-js#data-structure
- TV for display only, DataCube for data modifications (WIP)
- TV can display orders, and with the help of DC move them around (when implemented)
- Yes, If you connect Python to node.js using sockets and convert your data format 
- Overlays are data shaders. The only limit is your imagination.

Use **Segment** overlay to draw lines.

**Comment by Tiernan9** [comment]
Thanks for your answers ! OK, great, I will then look at a way to perform calculations and simulations in Python and display everything with TV. I guess I'll come toward you with more questions later, time to structure ... my imagination. 

PS : to draw lines, in the example you gave, I have retried this morning with what I thought I had previously done and it was working 

                `...
                 // If this is a SELL, draw the profit
                if (this.show_label && p[1] === 0 && prev) {
                    let profit = p[2] / prev[2] - 1
                    profit = (profit * 100).toFixed(2) + '%'
                    ctx.fillStyle = '#555'
                    ctx.font = '16px Arial'
                    ctx.textAlign = 'center'
                    ctx.fillText(profit , x, y - 25)
                    
                    //modifications
                    ctx.moveTo(x, y)
                    let x2 = layout.t2screen(prev[0])
                    let y2 = layout.$2screen(prev[2])
                    ctx.lineTo(x2, y2)
                    ctx.stroke()
                }
                .... `
