### ISSUE TITLE
No OLHC Data

### ISSUE THREAD

**Issue by Jufik** [C451/trading-vue-js#62]
Hello, 

thanks for the amazing lib! 
Great to see such open sourced quality charting tools . 

I plan to you use this - or my own fork - to display tick by tick data, so.... no OLHC.
Looking at your doc' - Data Structure Specificaly - I understand I cannot use VT to play with such data set. 

Could you confirm it is not possible as is ?
Is such possibility planned?

**Comment by C451** [comment]
Hi, why not? 

![ticks](https://user-images.githubusercontent.com/48596328/65409563-aa444080-ddf0-11e9-8de3-4b1688f628f4.png)

Sample 5 second bars from the tick data and use **Trades** overlay. There are different ways to do this, onchart, offchart, custom overlay. If you don't want to see OHLCV, just hide it.

**Comment by Jufik** [comment]
OK, thanks for your response, I'll give it a try, but to clarify: As-is, I don't plan to provide any OLHC data.

When playing around with samples, using [this data](https://github.com/C451/trading-vue-js/blob/master/data/data.json),  odd things happen when deleting OLHC data.

Providing couple of first candles:Charts is empty as soon as KPIs (EMAs in this sample) are off candles range.

Eventually, I found using `"type":"Spline` could workaround, but it looks like it still needs OLHC data (for the Legend I guess). I'll just go deeper to see what I'll end up with.

**Comment by C451** [comment]
Candlestick data is the foundation of this lib, so you cannot remove it completely (this will destroy the grid).
