### ISSUE TITLE
tulind 0.8.15 not installing

### ISSUE THREAD

**Issue by 1am** [C451/trading-vue-js#64]
Hello

I've wanted to run the tests to use them as examples so after cloning the trading-vue-js repo I ran `npm install` which failed with the following:

```
...
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.15/Release/tulind-v0.8.15-node-v64-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.15 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
...
npm ERR! Failed at the tulind@0.8.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```

This makes sense as the mentioned URL returns a 404.

I've changed the trading-vue-js package.json to use the latest version of tulind 0.8.18 and it seems to be working. Not sure if it hasn't broken anything but writing this to let know 👋

**Comment by C451** [comment]
Thanks for noticing, it is not a major dependency, but it's cool to be updated.
