### ISSUE TITLE
How to use it in React

### ISSUE THREAD

**Issue by kp13-kp13** [C451/trading-vue-js#65]
I am trying to explore and use your library in react. I have following code implemented:

`import 'trading-vue-js/dist/trading-vue'
import Data from './Data/data.json'

&#60;div className="App">
      &#60;trading-vue data={Data} width="500px" height="500px"></trading-vue>
&#60;/div>`
I am not able to display chart. Am I missing something here?

**Comment by C451** [comment]
Is it even possible? I mean this is a Vue.js component.

**Comment by kp13-kp13** [comment]
I dont think so. I was just trying to explore as I found it interesting and liked you library.
