### ISSUE TITLE
Precision of eight decimals show up as 0.00 on the y-axis

### ISSUE THREAD

**Issue by test513607a** [C451/trading-vue-js#67]
[data_3 - Copy (2).txt](https://github.com/C451/trading-vue-js/files/3888138/data_3.-.Copy.2.txt)
Can we increase the precision?

**Comment by C451** [comment]
We can and we should, this is a bug. 
And congrats, you are probably the first one to try a data of some s**t coin :D 

If you use decimal format (0.00000050) it will probably work.

**Comment by test513607a** [comment]
> And congrats, you are probably the first one to try data of some s**t coin :D
(Embarrassing Grin) 

>If you use decimal format (0.00000050) it will probably work.
The previous representations of my data used to be in terms of decimal rather than e-7 etc, and it was showing 0.00

**Comment by C451** [comment]
> (Embarrassing Grin)
How could I! Lmao, the only good project out there. 

> The previous representations of my data used to be in terms of decimal rather than e-7 etc, and it was showing 0.00

Yeah, will check this too.

**Comment by C451** [comment]
Check https://github.com/C451/trading-vue-js/commit/964e92d51af44b0eb54875cee49e15ba1daf2d2d

**Comment by test513607a** [comment]
Verified. Works Perfect.

1) data_sc.json - > really ? data_**s**hit**c**oin. lol
2) this is CELR data btw, not GRIN. took me a while before I understood your implication on the word
> (Embarrassing **GRIN**)

in the previous reply.
In all seriousness, Is GRIN really a great project ? 

Coder with wit huh, deadly combination!

**Comment by C451** [comment]
Depends on how you read it: **S**mall **C**ap also fits perfectly. :)

For a moment, I though it was GRIN data and it's embarrassing to call it a shitcoin. It made me laugh. Then I saw the wordplay and decided to leave it as is. Nothing against CERL btw.

Yeah, I think GRIN has potential. There are many reasons, some of them: default privacy, Rust, unconventional emission curve and, most importantly, mythology (like Bitcoin it has an unknown creator). The combination of all this can lead to success.   

Ty, though I don't consider myself a pure coder.
