### ISSUE TITLE
regression 0.3.6->0.4.2: time parsing issue?

### ISSUE THREAD

**Issue by laur89** [C451/trading-vue-js#68]
Looks like these 2 versions handle either time parsing or data placement on the timeline differently.
Use https://github.com/C451/trading-vue-101 for reproducing.

As-is (using lib v 0.3.6):
- first candle is correctly placed at 06:00 AM mark

Update lib to 0.4.2:
- first candle is now at 05:00.

**Comment by C451** [comment]
Actually, this was a big improvement to the time-axis https://github.com/C451/trading-vue-js/issues/50

**Comment by laur89** [comment]
Not completely following that ticket.
So we want to see UTC times on the timeline, that's the crux?

**Comment by C451** [comment]
Yes, UTC should be the primary time zone. We can spawn other timezones from it, this is an idea for a future update.
