### ISSUE TITLE
Implement proper zooming/scrolling

### ISSUE THREAD

**Issue by pps83** [C451/trading-vue-js#69]
> Scrolling & zooming as we all like

Really?.. All finance apps/chats totally suck and fail in scrolling/zooming. trading-vue-js is the same PoS.
Here's how scrolling & zooming has to work: https://www.google.com/maps (I hope you do agree that google maps scrolling and zooming does work the way we all like).
trading-vue-js totally doesn't work the way scrolling/zooming works in google maps.

The difference between gmaps and stock chart is that chart is simpler and doesn't really have vertical scrolling like in maps. Other than that, it should behave the same way.
These are the scrolling & zooming as we all like that doesn't exist in trading-vue-js:
 - you can drag gmap and then release mouse, and it will keep moving by itself (just like list of photos in your phone), and then you press mouse down to stop it from moving. This works in chartiq: https://demo.chartiq.com/
 - zooming is where every single chart lib TOTALLY fails. Afaik only old google finance (that's not available anymore) had it right. Here's how correctly implemented zooming works: no matter how much you zoom in or zoom out, your mouse ALWAYS points to the same location AND point that you mouse points to is the zoom point. That's the most important rule. Try it on google maps. I haven't seen any finance charting app that does it right. To have correct zooming trading-vue-js has to zoom-in/zoom-out using mouse wheel, and always keep the same time position under the mouse pointer. That is, if I rapidly zoom out from second bars to monthly chart and then again zoom in rapidly, I'll still see exactly the same chart position. Now try if with trading-vue-js: it has completely broken zooming that doesn't make any sense! 

IMO, to get it right, simply imagine that you have that endless horizontal chart. You want to make it possible for a user to navigate that chart fast and easy. Google maps does that for maps. I've implemented myself very similar mapping engine (for closed source military application) and I can tell you: nobody ever asked how to operate the map, as everybody knows how to zoom and scroll maps. If I made it a bit different than google maps, people would complain and wouldn't like it.
This part is critically important to get zooming working perfectly. I'll explain why, if my explanation wasn't clear. Open google maps showing entire united states: https://www.google.com/maps/@37.7371343,-95.0177018,6z
Now, what is the fastest way to zoom to central part of New York city? The fastest way is very simple: point your mouse over center of NYC and simply zoom fast. Done. You didn't need to adjust and zoom and pan you map 20 times to zoom to correct location at zoom levels of 100x from original map.
Now try the same with any stock chart: open [5 year GE chart](https://finance.yahoo.com/chart/GE#eyJpbnRlcnZhbCI6IndlZWsiLCJwZXJpb2RpY2l0eSI6MSwiY2FuZGxlV2lkdGgiOjcuOTg1ODY1NzI0MzgxNjI1LCJ2b2x1bWVVbmRlcmxheSI6dHJ1ZSwiYWRqIjp0cnVlLCJjcm9zc2hhaXIiOnRydWUsImNoYXJ0VHlwZSI6ImNhbmRsZSIsImV4dGVuZGVkIjpmYWxzZSwibWFya2V0U2Vzc2lvbnMiOnt9LCJhZ2dyZWdhdGlvblR5cGUiOiJvaGxjIiwiY2hhcnRTY2FsZSI6ImxpbmVhciIsInBhbmVscyI6eyJjaGFydCI6eyJwZXJjZW50IjoxLCJkaXNwbGF5IjoiR0UiLCJjaGFydE5hbWUiOiJjaGFydCIsInRvcCI6MH19LCJzZXRTcGFuIjpudWxsLCJsaW5lV2lkdGgiOjIsInN0cmlwZWRCYWNrZ3JvdWQiOnRydWUsImV2ZW50cyI6dHJ1ZSwiY29sb3IiOiIjMDA4MWYyIiwiZXZlbnRNYXAiOnsiY29ycG9yYXRlIjp7ImRpdnMiOnRydWUsInNwbGl0cyI6dHJ1ZX0sInNpZ0RldiI6e319LCJjdXN0b21SYW5nZSI6bnVsbCwic3ltYm9scyI6W3sic3ltYm9sIjoiR0UiLCJzeW1ib2xPYmplY3QiOnsic3ltYm9sIjoiR0UifSwicGVyaW9kaWNpdHkiOjEsImludGVydmFsIjoid2VlayIsInNldFNwYW4iOm51bGx9XSwic3R1ZGllcyI6eyJ2b2wgdW5kciI6eyJ0eXBlIjoidm9sIHVuZHIiLCJpbnB1dHMiOnsiaWQiOiJ2b2wgdW5kciIsImRpc3BsYXkiOiJ2b2wgdW5kciJ9LCJvdXRwdXRzIjp7IlVwIFZvbHVtZSI6IiMwMGIwNjEiLCJEb3duIFZvbHVtZSI6IiNGRjMzM0EifSwicGFuZWwiOiJjaGFydCIsInBhcmFtZXRlcnMiOnsid2lkdGhGYWN0b3IiOjAuNDUsImNoYXJ0TmFtZSI6ImNoYXJ0In19fSwicmFuZ2UiOm51bGx9) and try to zoom the same way on that huge green candle in April 2015:
![image](https://user-images.githubusercontent.com/1614246/71308883-cecdaa00-242b-11ea-8ecb-534fcd4f257c.png)
If you naturally expect that zooming should work the same way like in google maps, try it and you'll realize how broken it is. Same in trading view and everywhere else.

If you disagree with those my points, maybe you could suggest where and what I should change to make it work the way I described?

**Comment by pps83** [comment]
This is an example of properly working zoom in charts:
https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartForDiscontinuousIntraDay

**Comment by C451** [comment]
Idk, personally, I like this way of scrolling. As do the other 10M traders: https://www.tradingview.com/referral-program/ 

If you can't stand it, you are very welcome to make a fork and fix it. Btw, couldn't load the last example.

**Comment by pps83** [comment]
Are you saying that you couldn't open this one: https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartForDiscontinuousIntraDay
It appears that TradingView allows to use their charts and free on other sites. Interesting, their free basic charts actually have proper zoom implemented: https://www.tradingview.com/lightweight-charts/ try to zoom-in/zoom-out without moving your mouse: your chart will be back to where you looked at. With broken zoom this results in some random position.

**Comment by pps83** [comment]
I just found out that tradingview actually has this zoom implemented: if you hold Ctrl it will zoom on a candle. Can you also replicate that behavior?

**Comment by C451** [comment]
Yeah, it's possible, but not the main priority. Let's see if more ppl need this. There's too much stuff to implement, not much free time to do it all.

**Comment by pps83** [comment]
candle zoom the way trading view has it: https://github.com/C451/trading-vue-js/pull/82
for personal use, I definitely make this to be default.
