### ISSUE TITLE
More Efficient Auto Update?

### ISSUE THREAD

**Issue by AlexanderPeters** [C451/trading-vue-js#7]
I'm sure I'm missing something, as I haven't been able to dig as thoroughly into this project as I should; but here's my basic understanding. This repo is a combination of javascript code which runs locally via node and is displayed on a local port: 8080, the code then detects any changes to the data.json file and refreshes the page. The question I have is could some form of API or data pass through be implemented into the code to where I could just pass a JSON file of new points for the graph and each element to be appended onto the end of the graph and later saved to the data.json file (whether this be just the next candle or adding another 20 candles onto the end, same thing just appending to the graph), avoiding the need for a recompile each time I want to add a data point. -Very useful for efficient graph streaming.

**Comment by C451** [comment]
My suspicions were right (from the first issue): it seems you are trying to use this repo to develop your app (is it right?). 

If you need to embed this lib to your project, just install it with npm. It has an API interface (all you need to build custom charts) and you can just update your data from js. But you must do it reactively:   

  https://github.com/C451/trading-vue-js/blob/master/src/examples/Reactive.vue

If you are talking about the development of the lib itself, yeah, it needs some kind of playground editor that will simplify things. But for now it's TBA.

**Comment by AlexanderPeters** [comment]
Ok, thanks, will look into that.

**Comment by Tucsky** [comment]
> just the next candle or adding another 20 candles onto the end, same thing just appending to the graph), avoiding the need for a recompile each time I want to add a data point.

Big subject, imo. Exposing append & prepend methods would be super useful ! 
https://github.com/C451/trading-vue-js/blob/8df612c90dac0bde521e08a17afd03f87c13c819/src/components/Chart.vue#L223
Partial rendering of the candles & indicators etc...

**Comment by C451** [comment]
> > just the next candle or adding another 20 candles onto the end, same thing just appending to the graph), avoiding the need for a recompile each time I want to add a data point.
> 
> Big subject, imo. Exposing append & prepend methods would be super useful !
> [trading-vue-js/src/components/Chart.vue](https://github.com/C451/trading-vue-js/blob/8df612c90dac0bde521e08a17afd03f87c13c819/src/components/Chart.vue#L223)
> 
> Line 223 in [8df612c](/C451/trading-vue-js/commit/8df612c90dac0bde521e08a17afd03f87c13c819)
> 
>          data: { 
> 
> Partial rendering of the candles & indicators etc...

Yeah, I had this idea. The problem here is custom data structures, so user still needs to update all his data fields. 
```
Vue.$set()
``` 
is designed specifically for that. But I will think about set/append helpers. 

About partial rendering - the bottleneck is not rendering itself, but slicing (when data is huge)

**Comment by vab2048** [comment]
> If you need to embed this lib to your project, just install it with **npm**. It has an API interface (all you need to build custom charts) and you can update your data from js. But you must do it reactively:
> 
> https://github.com/C451/trading-vue-js/blob/master/src/examples/Reactive.vue

This link is now 404. Do you have a link to the most recent way of doing this?

**Comment by C451** [comment]
@vab2048 Hi, you can find it in earlier versions of the repo, but this example is more relevant: https://github.com/C451/trading-vue-js/blob/master/test/tests/DataHelper.vue
