### ISSUE TITLE
Area chart

### ISSUE THREAD

**Issue by Pa22** [C451/trading-vue-js#71]
Hello,
Is there any Area chart available for this project?
Also, is there any possibility to put buy and sell button?

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/tree/master/docs/api#data-structure-new

You can select the type `Spline` for the main chart. But it is also possible to use your own overlay, thus to build any kind of chart. 

> Also, is there any possibility to put buy and sell button?
Yes, in your app. TVJS is only a plotting library.
