### ISSUE TITLE
Error on getting chart data using DataCube

### ISSUE THREAD

**Issue by bettimms** [C451/trading-vue-js#75]
When calling this `DataCube.get('chart.data')` it's throwing:

TypeError: Cannot read property 'locked' of undefined.

![image](https://user-images.githubusercontent.com/9863453/71766984-bc6d6900-2f1f-11ea-9a95-740a30ec94d0.png)

![image](https://user-images.githubusercontent.com/9863453/71766989-cbecb200-2f1f-11ea-85c4-b83d9344956d.png)

When i call only `DataCube.get('chart')` i can see that the structure of the array is:
![image](https://user-images.githubusercontent.com/9863453/71767011-3bfb3800-2f20-11ea-8ea4-18dece254b1d.png)
 Could it be due to the `id` coming as  `chart.undefined`?! What could be missing during initialization?

**Comment by C451** [comment]
How do you initialise DC ? Could you post a minimal example here (with your data sample). It looks like the type is missing: https://github.com/C451/trading-vue-js/blob/master/src/helpers/dc_core.js#L94    

Plus, there is no `data` prop when you call `DataCube.get('chart')`

**Comment by bettimms** [comment]
Apparently was initializing it wrong.  Seems I had to do `new DataCube({chart: data})`. I was only filling `ohlcv` and initializing it like `new DataCube(data)`. So fixed it now.
Thanks for fast reply and this great job you've done.

**Comment by Mahmud1985** [comment]
Hi,I have similar problem with this.
Error shows blow:
Uncaught TypeError: Cannot read property 'filter' of undefined
at DataCube.query_search (dc_core.js:322)
at DataCube.get_by_query (dc_core.js:290)
at DataCube.get (datacube.js:64)
at VueComponent.keydown (Toolbar.vue?./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options:77)

my code making error: let dc = new DataCube()
dc.get('.') 

codes and data just use 101 project's.
