### ISSUE TITLE
Logarithmic scale display support?

### ISSUE THREAD

**Issue by backnight** [C451/trading-vue-js#76]
Everything is in the title.

The logarithmic scale is very important for crypto assets price charts ;)

**Comment by C451** [comment]
Oh yeah! https://github.com/C451/trading-vue-js/projects/1#card-24578548

**Comment by backnight** [comment]
Sorry, I didn't checked the "Projects" section on Github.

My bad !

**Comment by C451** [comment]
@backnight Np!
