### ISSUE TITLE
Strange canvas drawing output

### ISSUE THREAD

**Issue by fg123** [C451/trading-vue-js#77]
Please let me know what other info you need about my setup, but this is the result I'm getting when I move my mouse around the area; seems like an internal canvas drawing issue? Furthermore, when I resize the screen, the width and height updates but the canvas is cleared, until I move my mouse back over it; at which point the data reappears. 

![image](https://user-images.githubusercontent.com/585803/72190564-d4d0fe00-33cd-11ea-98e2-f06798441962.png)

Not sure if it's DOM or data or config issue.

```
<template>
    <div class="wrapper" ref="wrapper" style="width: 100%; height: 100%">
        <TradingVue :data="this.$data" :height="height" :width="width">

        </TradingVue>
    </div>
</template>
<script>

module.exports = {
    components: { TradingVue: require('trading-vue-js').default },
    props: {
        chartData: Object
    },
    mounted() {
        this.setSize();
        new ResizeObserver(this.setSize).observe(this.$refs['wrapper']);
    },
    methods: {
        setSize() {
            this.width = this.$refs['wrapper'].offsetWidth;
            this.height = this.$refs['wrapper'].offsetHeight;
        }
    },
    computed: {
        dataset() {
            return this.chartData.dataset;
        }
    },
    watch: {
        dataset: function(newData) {
            if (newData.length === 1) {
                console.log("Setting new data!", newData[0].history.length);
                this.$set(this.chart, 'data', newData[0].history);
            }
        }
    },
    data() {
        return {
            "chart": {
                "type": "Candles",
                "data": []
            },
            width: 0,
            height: 0
        }
    }
}

</script>
```

```
"trading-vue-js": "^0.4.3",
"vue": "^2.5.21",
```

**Comment by C451** [comment]
Yeah, it's a known issue: https://github.com/C451/trading-vue-js/issues/63 
It appear only on some setups. The only solution I came up with is to disable retina support (optionally).

**Comment by fg123** [comment]
Looks like if I set my Chrome zoom to below 100% the bug will appear; anything above 100% (devicePixelRatio >= 1) works fine; can you see if that would reproduce the bug on your end?

**Comment by C451** [comment]
@fg123 yo!! thanks man, who would've thought! The bug's been unsolved for a several month and now I can finally fix it.

Big TY!
