### ISSUE TITLE
Candles scrunch together when different timing in data

### ISSUE THREAD

**Issue by fg123** [C451/trading-vue-js#78]
If I have a bunch of historical data in 1 day ticks and then have more up to date (i.e. 5 minute tick) data close to "now", the candles render like this:
![image](https://user-images.githubusercontent.com/585803/72322495-77120f80-3674-11ea-8529-1d922b36b09b.png)

Is the maximum resolution of the charting to daily? Is there a way for it to consolidate the candles without rendering them all like that unless the resolution is zoomed in more?

**Comment by C451** [comment]
The main chart aka OHLCV must have a constant time-step (gaps are accepted), this is a requirement. So the only way to implement that is to consolidate candles before feeding them into the library.

**Comment by fg123** [comment]
Ah, I think this commit https://github.com/C451/trading-vue-js/commit/b783860daa5d089ce8eed3e86a23384fb0427ed7 might solve my issue; is there a timeline for the next release?

**Comment by C451** [comment]
Good, there is no fixed date/timeline but I plan to add features gradually.

**Comment by fg123** [comment]
The issue seems to be that the old algorithm uses the first 100 data points to determine the spacing, which in my case will be day by day, but my last bit of data is in 5 minute spacing, which means the library assumes the data will be minimum 1 day (leading to the scrunched up ticks). If the algorithm uses the entire dataset to determine the minimum spacing (as per the commit I referenced) it should setup the chart to use 5 minute spacing instead and allow the gaps in the 1 day spacing data; if I understand it correctly?

**Comment by C451** [comment]
@fg123 `let len = Math.min(ohlcv.length - 1, 99)` It still uses the first 99 points. It seems that you're trying to trick the library... I'd suggest you to make a fork and experiment with it.
