### ISSUE TITLE
Waiting for Custom Draw Draw tools :(

### ISSUE THREAD

**Issue by stoxalpha** [C451/trading-vue-js#79]
Even the beginners draw tools for Horizontal Line, Trend Line and Parallel Channel will be extremely helpful :)

**Comment by C451** [comment]
They are already there: https://c451.github.io/trading-vue-demo/ 
It's possible to make almost any tool with the current API. But I decided to limit the scope of the built-in set (Segment, Line and Percent Measurement tool).
