### ISSUE TITLE
Parameter Config File?

### ISSUE THREAD

**Issue by AlexanderPeters** [C451/trading-vue-js#8]
Would it be possible to add a configuration file, that is used on startup. A few useful features I can think of immediately to include in the config file would be the local port that you want to launch the graph on (8080 might already be in use) and which input data JSON file you want to use (a path to a specific file) as you might want to keep multiple but, different data.json files around and select which one to use on startup. --It might be more useful to have these as command line parameters when building with npm if possible, default values could be what's hardcoded now.

**Comment by C451** [comment]
Consider to make your custom project and just install tv.js with **npm**

You can just clone this: https://github.com/C451/trading-vue-101 
(minimal environment with tv.js installed as dependency)

BTW you can change the port in webpack config.

**Comment by AlexanderPeters** [comment]
I'll figure out file selection later, port config added.
