### ISSUE TITLE
Crosshair position is affected by window position

### ISSUE THREAD

**Issue by ric-h** [C451/trading-vue-js#83]
Hi, first of all, thanks for the amazing lib.

I'm using the chart inside a window and the crosshair position is being affected by the position of the window. The more I move the window to the right, the more the crosshair is out of alignment with the mouse cursor, showing wrong informations about the candle.

![tradingvue-cursor](https://user-images.githubusercontent.com/4774293/74471796-97093e80-4e7f-11ea-969a-b891b4e75403.png)

**Comment by C451** [comment]
Probably a bag, need to check

**Comment by ric-h** [comment]
Hi, the source of the problem is the use off css transform:

`.the_DIV_around {
    position: absolute;
    transform: translate3d(317px, 10px, 0px);
}`

**Comment by C451** [comment]
Yeah, the lib cannot parse css transforms.

**Comment by C451** [comment]
Closing for now

**Comment by C451** [comment]
Support of transforms (translate only) https://github.com/tvjsx/trading-vue-js/commit/1287d36e9ee2b0e6f52c13ba953d48acae899e4c
