### ISSUE TITLE
Candle wick thickness

### ISSUE THREAD

**Issue by Frou-HOS** [C451/trading-vue-js#86]
Hello @C451 ,

Thanks for this awsome work !!

A question, it's possible to increase the wicks of a candle ? I didn't see anything about this.
Take a look on my screen wicks are very thin
![image](https://user-images.githubusercontent.com/13420553/75053114-0363ed80-54d1-11ea-944d-016b410235da.png)

**Comment by C451** [comment]
Did you change the default color? Props:
```
colorWickUp
colorWickDw
```
I can see them, but the color is too bright.

**Comment by Frou-HOS** [comment]
No I didn't change anything about the default wick color.
When I change it with a black color or blue color with this variable, it didn't change anything too.

**Comment by Frou-HOS** [comment]
So i re-install all my base project (electron/vue/vuetify) and now the Wicks are corrects
![image](https://user-images.githubusercontent.com/13420553/75097597-cec56400-55ac-11ea-8ac9-7cd01b909f44.png)

I don't know why this thin wicks appear, maybe lot of install/reinstall dependencies ... 

If you want to investigate i can give you my dirty start project ;)

Thanks for your response, and your time

**Comment by C451** [comment]
Thanks, but I think it will be hard to reproduce.
