### ISSUE TITLE
easier install??

### ISSUE THREAD

**Issue by ms1110** [C451/trading-vue-js#88]
Sorry for this not-specialist-question: Can't I just copy the files to my webserver and make it running?

**Comment by C451** [comment]
Yes, https://github.com/C451/trading-vue-demo use it as a boilerplate.

**Comment by ms1110** [comment]
Thank you but it doesn't work. Just an empty, black site with a checkbox and NM...

**Comment by ms1110** [comment]
Now I got it: trading-vue.min.js and data.json must com from https://c451.github.io/trading-vue-demo/ ... ??? If I can't use my own data, it makes no sense.

**Comment by ms1110** [comment]
Now I tested once more: it works if I load trading-vue.min.js and json from https://github.com/C451/. It makes no sense if I can't use my own data.

**Comment by C451** [comment]
Do you know how to build js / Vue.js apps ? It's a good idea to start from there. 

TradingVueJs is Vue.js component, thus you should know how to use the framework.

**Comment by ms1110** [comment]
Sorry, but I'm not a programmer and just want to do some financial analysing. What a pity, your project looks really cool.

**Comment by ms1110** [comment]
What I never understand: you (and other people) invest so much time to build really great software. And you encourage others to use it. Fantastic! But why on earth do you do it in a way, that 90 % of all potential users could not use it?

**Comment by C451** [comment]
@ms1110 This particular project was initially built for my purposes (I'm an algo trader). So, this project is for people who know how to code. 

Also, I respect my time. Imagine making this project for free (several month of coding, 12k lines of code) and also helping anyone with any question.
