### ISSUE TITLE
colorVolUp,colorVolDw color issue

### ISSUE THREAD

**Issue by vishnug1995** [C451/trading-vue-js#89]
why colorVolUp,colorVolDw showing black when i use it in electron vue 
![image](https://user-images.githubusercontent.com/31384107/76136970-a2eeb780-605d-11ea-972e-dad4dc9f4feb.png)

but the same code work perfectly in browser 
![image](https://user-images.githubusercontent.com/31384107/76136986-c4e83a00-605d-11ea-8d62-8feb221690f0.png)

this is my example code

                   <template>
           <trading-vue :data="chart" :width="this.width" :height="this.height"
        :toolbar="true"
        :overlays="overlays"
        :color-back="colors.colorBack"
        :color-grid="colors.colorGrid"
        :color-text="colors.colorText">
    </trading-vue>

    </template>

    <script>
    import {TradingVue, DataCube}  from 'trading-vue-js'
    import PerfectTrades from './PerfectTrades.js' // New import

    export default {
        name: 'app',
        components: { TradingVue },
        methods: {
            onResize(event) {
                this.width = window.innerWidth
                this.height = window.innerHeight
            }
        },
        computed: {
          colors() {
              return this.night ? {} : {
                  colorBack: '#fff',
                  colorGrid: '#eee',
                  colorText: '#F42F54'
              }
          },
        },
        mounted() {
            window.addEventListener('resize', this.onResize)
        },
        beforeDestroy() {
            window.removeEventListener('resize', this.onResize)
        },
        data() {
            return {
                chart: new DataCube({
                    ohlcv: [
                        [
                            1555495200000,
                            5247.41020556,
                            5268.8,
                            5235,
                            5259.9,
                            217.6127009
                        ],
                        [
                            1555498800000,
                            5259.9,
                            5297.9,
                            5258.5,
                            5290,
                            315.15404971
                        ],
                        [
                            1555502400000,
                            5290,
                            5300,
                            5211.8,
                            5232,
                            631.05331034
                        ],
                        [
                            1555506000000,
                            5231.95877257,
                            5251.6,
                            5221.7,
                            5248.2,
                            298.31253802
                        ],
                        [
                            1555509600000,
                            5248.2,
                            5252.9,
                            5221,
                            5252.57663148,
                            284.03112872
                        ],
                        [
                            1555513200000,
                            5252.57663148,
                            5269.6,
                            5247,
                            5251.9,
                            327.21120598
                        ],
                        [
                            1555516800000,
                            5251.8,
                            5260,
                            5240.14211397,
                            5252.3,
                            165.77947801
                        ],
                        [
                            1555520400000,
                            5252.2,
                            5275.7,
                            5247.3,
                            5262.6,
                            230.86538508
                        ]
                    ]
                    , onchart: [], offchart: []
                }),
                width: window.innerWidth,
                height: window.innerHeight,
                night: false,
                overlays: [PerfectTrades]
                
            }
        }
    }
    </script>

**Comment by C451** [comment]
Interesting, I use the lib with electron - everything is ok. Try to set the colors explicitly.

**Comment by C451** [comment]
No further feedback, closed.
