### ISSUE TITLE
Make data set/append helpers

### ISSUE THREAD

**Issue by C451** [C451/trading-vue-js#9]
> just the next candle or adding another 20 candles onto the end, same thing just appending to the graph), avoiding the need for a recompile each time I want to add a data point.

Big subject, imo. Exposing append & prepend methods would be super useful ! 
https://github.com/C451/trading-vue-js/blob/8df612c90dac0bde521e08a17afd03f87c13c819/src/components/Chart.vue#L223
Partial rendering of the candles & indicators etc...

_Originally posted by @Tucsky in https://github.com/C451/trading-vue-js/issues/7#issuecomment-485255757_

**Comment by tiagosiebler** [comment]
An extended sample that uses ccxt as a candle source would be a nifty real-life async demonstration of this:
https://github.com/ccxt/ccxt#javascript-for-use-with-the-script-tag

Each range-stretch could trigger a REST API request to fill that missing gap.

**Comment by C451** [comment]
Yep, I got an idea. I'm not sure about including a third party API, but a simple callback will certainly do the job.

**Comment by va-prans** [comment]
If someone is still looking for a solution i got it working by adding an @mouseup event on a div that wraps the vue component like so. 
```
<div @mouseup="onChartMouseRelease" class="chartDiv">   
<trading-vue
        :data="chartContainer"
        :width="this.width"
        :height="this.height"
        ref="tradingVue">
</trading-vue>
</div>
```
the event fires off this method 
```
onChartMouseRelease(event) {
      console.log("mouse released.");
      this.rangeCheck();
    },
```
which then checks if more data needs to be fetched 
```
rangeCheck: function() {
      var range = this.$refs.tradingVue.getRange();
      if (range[0] < this.chartContainer.chart.data[0][0]) {
        console.log("get more data..");
        this.fetchMoreData();
      }
    }
```
and finally get the data somehow and unshift it to the chart data array
```
fetchMoreData: function() {
      var startTs = this.chartContainer.chart.data[0][0];
      var tf = this.getCurrentTfInt();
      axios
        .get(
          BASE_URL +
            "/Home/GetPreviousMarketData?timeStamp=" +
            startTs +
            "&timeFrame=" +
            tf +
            "&count=100"
        )
        .then(res => {
          console.log(JSON.stringify(res.data.data));
          this.chartContainer.chart.data.unshift(...res.data.data);
        })
        .catch(err => console.log(err));
    }
```

**Comment by C451** [comment]
Nice! Hopefully, DataCube will make this process easier. Currently WIP.

**Comment by hoangvanlong5342** [comment]
Hi @C451 
When you fix this issue?
Thanks

**Comment by hoangvanlong5342** [comment]
> DataCube

How to use DataCube?

**Comment by C451** [comment]
Hello @hoangvanlong5342 idk when exactly, but when it's done, it will be a bloody powerful tool. 

See the progress: https://github.com/C451/trading-vue-js/blob/master/src/helpers/datacube.js
API is undocumented for now.

**Comment by hoangvanlong5342** [comment]
Hi @C451 
when do you update document for new api?

**Comment by C451** [comment]
Timing is the hardest part. Now the data helper is unstable/experimental, the API may change. When you see at least half of the checkmarks filled, you can expect some docs: https://github.com/C451/trading-vue-js/projects/1

**Comment by thenewspacesky1990** [comment]
Hi @C451 
I like this feature. 
How to use this library on NuxtJS?

**Comment by C451** [comment]
Hi @thenewspacesky1990, unfortunately I haven't tried it myself yet. Are there any requirements for that?

**Comment by zmohamed200133** [comment]
Really good. I'm waiting for this function
When will you finish?
Thanks

**Comment by C451** [comment]
@learntolearn99 I think you can

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/blob/master/test/tests/DataHelper.vue

An example of connection to an exchange. (Unstable, there may be errors)

**Comment by C451** [comment]
DataCube handles the basic operations, close.
