### ISSUE TITLE
timezone issue when using node binance api

### ISSUE THREAD

**Issue by vishnug1995** [C451/trading-vue-js#91]
The node binance api (https://github.com/jaggedsoft/node-binance-api) , giving utc time stamp when i using the  ,
          
              binance.candlesticks("BNBBTC", "5m", (error, ticks, symbol) => {
	            let [time, open, high, low, close, volume, closeTime,assetVolume,trades,buyBaseVolume, 
	            console.log(time)
	         }, {limit: 500});

 but my timezone is +5.30 is any way to convert to IST timezone

![image](https://user-images.githubusercontent.com/31384107/76190465-0cf49180-6203-11ea-85df-30f3f6cb7f27.png)

my current time is 
![image](https://user-images.githubusercontent.com/31384107/76190499-21d12500-6203-11ea-9b15-c6d6abe1e084.png)

is any possibilties to convert the utc timestamp

**Comment by C451** [comment]
For now the library supports only UTC, but the timezone thing is on the roadmap.

**Comment by vishnug1995** [comment]
so , what i do now... any help please....

**Comment by C451** [comment]
it's a waiting game if you don't want to make a fork. The place to look is here : https://github.com/C451/trading-vue-js/blob/master/src/components/js/botbar.js#L97
