### ISSUE TITLE
how to subscribe onVisibleRangeChanged callback, As the chart slides to the left loading more  data....

### ISSUE THREAD

**Issue by activeliang** [C451/trading-vue-js#93]
or any other way???

**Comment by C451** [comment]
For now it's a bit verbose, need to simplify: 
```
this.$refs.tradingVue.$refs.chart.$on('range-changed', this.range_changed)
```

`this.$refs.tradingVue` - in your parent component with the TVJS ref.

**Comment by activeliang** [comment]
thx~

**Comment by C451** [comment]
https://github.com/C451/trading-vue-js/commit/f37842e53259124a8f3dac17597f5d8ca09a6f77
