### ISSUE TITLE
How can i add price line to spline to track the latest price?  Like candles chart

### ISSUE THREAD

**Issue by activeliang** [C451/trading-vue-js#96]
I know I can draw it by overlay, but I want to display it in the price Range bar, but I don't know how to operate it.
![WX20200323-151042](https://user-images.githubusercontent.com/24507358/77291438-393b0280-6d19-11ea-9af9-d27dbc7a6189.png)

**Comment by C451** [comment]
This, https://github.com/C451/trading-vue-js/blob/master/docs/api/SHADERS.md
And this, https://github.com/C451/trading-vue-js/blob/master/src/components/overlays/Candles.vue#L19

**Comment by activeliang** [comment]
It turned out that I didn't read the documents carefully, and my problem was solved, although there was a performance problem when there was a lot of data.  Thank you for your patience and help

**Comment by C451** [comment]
Your chart looks great. Yeah, performance needs to be improved.

**Comment by C451** [comment]
@activeliang if for some reason you'd like to open source your overlays, you are welcome here: https://github.com/tvjsx/tvjs-overlays  

The idea is to create big library of overlays for tvjs powered by the community.
